version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-auth
    ports:
      - "6379:6379"
    environment:
      REDIS_USER: "${REDIS_USER}"
      REDIS_PASSWORD: "${REDIS_PASS}"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--port", "6379" ]
    volumes:
      - redis-data:/data
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=${REDIS_USER}:redis:6379
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - "8082:8081"

volumes:
  redis-data:
    driver: local
