version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis-auth
    ports:
      - "6379:6379"
    environment:
      REDIS_USER: "${REDIS_USER}"
      REDIS_PASSWORD: "${REDIS_PASS}"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--port", "6379" ]
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
    driver: local
